name: yelpax_pro
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  animated_custom_dropdown: ^3.1.1
  logger: ^2.6.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/y_logo.png"
  android: true
  ios: true



  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
    - assets/images/splash_1.jpg


  # example:
  fonts:
    - family: Inter
      fonts:
      
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-Italic.ttf
          style: italic
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-Italic.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

